### ISSUE TITLE
Не работает с MySQL

### ISSUE THREAD

**Issue by thescs** [Alexell/metadmin_ex#2]
Почему метадмин может не подключаться к базе MySQL? По идее он должен сам таблицы нужные создать, если данные указаны правильно. До перевода на MySQL использовалась sv.db. Ошибок в консоли при этом никаких нет, а из изменений на сервере перестал работать только профиль !pr.

**Comment by Alexell** [comment]
Опишите проблему подробнее. Вы правильно делали подключение? На сервере в метадмине через меню прописываете данные MySQL, сохраняете, потом меняете SQL на MYSQL и перезагружаете сервер. БД должна быть чистая, точнее в ней не должно быть табличек метадмина. После запуска сервера, подключитесь к нему, чтобы сработал хук, в БД должны будут появиться таблицы.

Подключение к MySQL выполняется при запуске сервера?
В БД были автоматически созданы таблицы?
Игроки заносятся в таблицу ma_players?

**Comment by thescs** [comment]
Сначала выставлялся тип подключения, затем параметры. После этого перезапуск. База в БД грязная, но без таблиц с префиксом ma_.

**Comment by Alexell** [comment]
Ответы на остальные вопросы?

**Comment by Alexell** [comment]
Подключение к MySQL выполняется при запуске сервера (пишется в консоли)?
В БД были автоматически созданы таблицы? Если да, то все ли?
Игроки заносятся в таблицу ma_players?

**Comment by thescs** [comment]
В консоли только информация о том что mysqloo загружен. Таблицы не были созданы. Игроки не заносятся.

**Comment by thescs** [comment]
![Screenshot_20200525-130808](https://user-images.githubusercontent.com/5880496/82803230-d684f500-9e88-11ea-8e95-ce55789d640b.png)
Так выглядит сейчас конфиг метадмина в sv.db

**Comment by Alexell** [comment]
На вашем скриншоте ничего не видно. Но не суть.
Если аддон установлен на сервере, в настройках MySQL прописаны корректные данные для подключения и выбран тип MySQL для хранения данных и вы не видите в консоли сообщение "MetAdmin MySQL: Connected!" - значит вы что-то сделали не так. Либо неверно указали данные для подключения, либо, если сервер MySQL не находится на одной машине с сервером Метростроя, может быть выключен удаленный доступ к БД. В общем проблема никак не связана с самим аддоном.

Последняя версия аддона проверялась мною лично на нулевом сервере Метростроя, подключение к MySQL и заполнение таблиц происходит корректно.

**Comment by Alexell** [comment]
**P.S.** Я больше не занимаюсь разработками для Метростроя, больше не будет обновлений аддонов (разве что мелкие). У меня есть сервер Метростроя, где работают эти аддоны и на текущий момент все работает исправно.
Оказывать содействие в решении смежных проблем, не имею возможности.
